Issue 123 - Instagram and Tiktok embed
hlxsites/petplace pull request #146
Opened 2023-06-06 16:46 UTC by varunmitra

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #123 

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/cats/pet-care/neko-cat-cafe
- Tiktok: https://issue-123--petplace--hlxsites.hlx.page/article/cats/pet-care/neko-cat-cafe
- Instagram: https://issue-123--petplace--hlxsites.hlx.page/article/general/just-for-fun/valentines-for-your-pet

2023-06-06 19:38 UTC, travrob1 commented on blocks/embed/embed.css
> +  main .embed.embed-twitter .twitter-tweet-rendered {
the use of `main` in every style is unnecessary... You are already prefixing all your styles with `.embed` which is sufficent.

2023-06-06 19:43 UTC, travrob1 requested changes

2023-06-06 19:43 UTC, travrob1 commented on blocks/embed/embed.js
> +          console.error('[Embed] Error parsing data: ', e);
add // eslint-disable-next-line no-console
otherwise linter will always show warnings.

/home/runner/work/petplace/petplace/blocks/embed/embed.js
Warning:   133:11  warning  Unexpected console statement  no-console
Warning:   138:9   warning  Unexpected console statement  no-console

2023-06-06 19:43 UTC, travrob1 commented on blocks/embed/embed.js
> +        console.debug(`[Embed/${conf.id}] message: `, data);
same as above.

2023-06-06 19:45 UTC, travrob1 commented
The embeds look great by the way. nice work.

2023-06-06 20:01 UTC, mfrisbey reviewed
Agreed, the embeds look great! I left a couple comments, but please let me know what you think.

2023-06-06 20:01 UTC, mfrisbey commented on blocks/embed/embed.js
> +    block.classList = 'block embed';
Is the intent here to replace the `classList` or add to it? If we're adding to it, `block.classList.add('block', 'embed')` might be safer.

2023-06-06 20:07 UTC, travrob1 commented on blocks/embed/embed.js
> +    <iframe src="${url.href}" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;" allowfullscreen=""
Good catch... Yeah i wold definitely suggest just adding a class... and moving the styles to a css file

2023-06-07 17:35 UTC, varunmitra commented on blocks/embed/embed.js
> +    <iframe src="${url.href}" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;" allowfullscreen=""
Block is based on the embed block that's part of helix-block-collection. I see similar syntax used in there as well: https://github.com/adobe/helix-block-collection/blob/main/blocks/embed/embed.js#LL33C15-L33C15

2023-06-07 18:11 UTC, varunmitra commented on blocks/embed/embed.js
> +    tiktok.outerHTML = json.html;
Tiktok api send back a json response that contains html code, it will be difficult to change the html code to nodes. This is a common approach as far as tiktok embed goes. I have seen it being used [bambooHR](https://github.com/hlxsites/bamboohr-website/blob/5eea556339016d8dd4a9480a5c89805ca2f551fa/blog/blocks/embed/embed.js#L72) & [tmg](https://github.com/hlxsites/tmg-ucm/blob/6cc0120e5460d0a4d3b9cc87b6f1e60cc48868ae/blocks/embed/embed.js#L63)

2023-06-26 18:28 UTC, varunmitra commented on blocks/embed/embed.css
> +    height: 462px;
set aspect ratio to 4/5, default for Instagram posts in portrait mode

2023-06-27 17:15 UTC, merged