Feature/ppad 14 adoption landing dok
hlxsites/petplace pull request #396
Opened 2024-02-19 18:53 UTC by hero-dokane

**Jira Ticket:** PPAD-14

**Purpose**: Adoption Landing Page functionality

**Demo**: http://localhost:3000/pet-adoption/

2024-02-20 14:52 UTC, ericvangeem requested changes

2024-02-20 14:52 UTC, ericvangeem commented on blocks/adopt-search/adopt-search.js
> +  const baseUrl = 'https://api-stg-petplace.azure-api.net/';
@raymond-p-sanford @hero-dokane @jane-li-hero Can we abstract this API URL to some common module? Since these are Stage API hosts, and knowing at some point we'll need to switch to referencing Prod API hosts, it would be ideal if that determination is managed in one central place. We might have a common module that contains logic to return either a Stage API host or Prod API host based on the current site URL.

2024-02-20 14:52 UTC, ericvangeem commented on blocks/adopt-search/adopt-search.js
> +      <h3 class='pet-card-name'><a href='/pet-adoption/pet/${clientId}/${animalId}' class='stretched-link'>${Name?.replace(
@hero-dokane @raymond-p-sanford @jane-li-hero in the URL, replace `/pet` with the plural lower-cased animal type. Also, swap the `${animalId}` and `${clientId}` values in the URL. 
For example, for an animal with these values: 
- `Animal type` = "Dog"
- `animalId` = "abc"
- `clientId` = "123"  

then the URL should be `/pet-adoption/dogs/abc/123`

Since this pet card rendering is used in multiple places (landing page, search results, pet detail page), it might make sense to export this as a common module that other blocks can call.

2024-02-20 14:56 UTC, ericvangeem commented on blocks/adopt-search/adopt-search.js
> +      <h3 class='pet-card-name'><a href='/pet-adoption/pet/${clientId}/${animalId}' class='stretched-link'>${Name?.replace(
Just sharing for reference, the Pet Detail URL is documented here https://herodigital.atlassian.net/wiki/spaces/PA/pages/3372122366/Pet+Details#URL-Structure

2024-02-21 15:13 UTC, ericvangeem requested changes

2024-02-21 15:13 UTC, ericvangeem commented on blocks/adopt-search/adopt-search.js
> +      numResults: 4,
@hero-dokane @raymond-p-sanford tech design is to request 50 `numResults` and use JS to randomly select 4 from that list. https://herodigital.atlassian.net/wiki/spaces/PA/pages/3371729078/Landing+Page#Adoptable-Pets

Example code snippet:
```
function getRandomObjects(array, count) {
  const shuffled = array.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

const objects = [
  { id: 1, name: 'Object 1' },
  { id: 2, name: 'Object 2' },
  { id: 3, name: 'Object 3' },
  { id: 4, name: 'Object 4' },
  { id: 5, name: 'Object 5' },
  { id: 6, name: 'Object 6' },
  { id: 7, name: 'Object 7' },
  { id: 8, name: 'Object 8' }
];

const randomObjects = getRandomObjects(objects, 4);
console.log(randomObjects);
```

2024-02-22 14:28 UTC, raymond-p-sanford commented on blocks/adopt-search/adopt-search.js
> +      numResults: 4,
@hero-dokane This looks good now.  Thanks

2024-02-22 14:29 UTC, raymond-p-sanford commented on blocks/adopt-search/adopt-search.js
> +      <h3 class='pet-card-name'><a href='/pet-adoption/pet/${clientId}/${animalId}' class='stretched-link'>${Name?.replace(
Looks good

2024-02-22 14:29 UTC, merged