Feature/PPAD-23 Pet Profile
hlxsites/petplace pull request #404
Opened 2024-02-22 19:07 UTC by jane-li-hero

Jira Ticket: PPAD-23

Purpose: Pet Profile functionality

Test URLs: 
https://feature-ppad-23_pet-profile_jl--petplace--hlxsites.hlx.page/pet-adoption/dogs/40596030/PP1008
http://localhost:3000/pet-adoption/dogs/40596030/PP1008

2024-02-22 19:25 UTC, ericvangeem requested changes

2024-02-22 19:25 UTC, ericvangeem commented on blocks/pet-details/pet-details.js
> +    const petDetailPageUrl = `/pet-adoption/${animalType}/${animalId}/${clientId}`
@jane-li-hero @raymond-p-sanford this URL is slightly incorrect according to the [tech design](https://herodigital.atlassian.net/wiki/spaces/PA/pages/3372122366/Pet+Details#URL-Structure). We need to lower-case the `animalType` value and append an `s` character to it. 

Currently: `https://feature-ppad-23_pet-profile_jl--petplace--hlxsites.hlx.page/pet-adoption/Dog/51730061/PP4`
Expected: `https://feature-ppad-23_pet-profile_jl--petplace--hlxsites.hlx.page/pet-adoption/dogs/51730061/PP4`

2024-02-22 19:25 UTC, ericvangeem commented on blocks/pet-details/pet-details.js
> +    const animalApi = 'https://api-stg-petplace.azure-api.net/animal/';
@jane-li-hero @raymond-p-sanford I believe @hero-dokane implemented a module to get the base API host name. Can you please work with him to use the approach he defined? Please update all API base URLs within your code to use this common approach.

2024-02-23 15:08 UTC, ericvangeem approved these changes

2024-02-23 15:20 UTC, raymond-p-sanford approved these changes

2024-02-23 15:21 UTC, merged