bugfix: dogtv modal close button
hlxsites/petplace pull request #493
Opened 2024-05-03 18:38 UTC by ankyc-phi

Branch Commits:
- moved close button inside popup
- css changes for the button

Jira Issue:
https://pethealthinc.atlassian.net/browse/PM-263

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/
- After:
  - https://bugfix-dogtv-modal--petplace--hlxsites.hlx.live/
  - https://bugfix-dogtv-modal--petplace--hlxsites.hlx.live/?martech=off

Screenshots:

![image](https://github.com/hlxsites/petplace/assets/146023473/e4b13723-77d6-4124-9fc6-c7e1a1119a1a)
![image](https://github.com/hlxsites/petplace/assets/146023473/e4ed0f2a-ec41-4ef4-9e1f-43fbd83fcf80)

2024-05-12 13:56 UTC, ramboz requested changes

2024-05-12 13:56 UTC, ramboz commented on scripts/aria/aria-dialog.js
> +    const closeBtn = document.createElement('button');
The `aria-dialog.js` is meant to be a fully generic widget independent of the project. I'd suggest moving these customizations to `loadNewsletterPopup` in `scripts.js` instead.

2024-05-16 00:39 UTC, ramboz approved these changes

2024-05-16 00:39 UTC, ramboz commented on scripts/scripts.js
> +  await decorateBlock(popupBlock);
I think decorateBlock is just sync by default, you probably don't need the `await` here

2024-05-16 04:44 UTC, ankyc-phi commented on scripts/scripts.js
> +  await decorateBlock(popupBlock);
i had done the await since i was putting my code after that, but i moved my code block at the end and forgot to remove the await

2024-05-16 04:44 UTC, ankyc-phi commented
@ramboz merging this into the deploy branch

2024-05-16 05:13 UTC, merged