81752 table component
hlxsites/petplace pull request #622
Opened 2024-07-30 15:28 UTC by mat3usps

![image](https://github.com/user-attachments/assets/e3463d0f-aae9-4400-a17f-a013939ae389)

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/
- After:
  - https://81752-table-component--petplace--hlxsites.hlx.live/
  - https://81752-table-component--petplace--hlxsites.hlx.live/?martech=off

2024-07-30 22:51 UTC, yuliaribeiro requested changes
Mateus good job :)
I did a generic review, but when I was reviewing the table a saw an implementation that I wasn't sure.
I left there a comment so @darlantc can evaluate better how we should proceed.

2024-07-30 22:51 UTC, yuliaribeiro commented on react-client/src/components/design-system/text/Title.tsx
> +  fullWidth?: boolean;
I have similar opinion about the fullWidth.. Using it we can accidentally change the line-height and letter-spacing, the text or title shouldn't worry about width

2024-07-30 22:51 UTC, yuliaribeiro commented on react-client/src/routes/playground/playgrounds/ConditionalPlayground.tsx
I'm really not fan of this component..
Let's discuss with the team if we really need to implement in the project..
So, here in the playground you are using 3 text, but the playground is rendering 2.
I needed to open the code to understand the logic why is showing and in what conditions.
My suggestion when writing playgrounds would be think about someone that needs to test the element without opening code to understand the logic.. If the team decides to maintain this Conditional, you can add buttons or select with options containing the "condition" when text will appear and when not.

2024-07-30 22:51 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
I saw that you implemented on the Table the functionality to select items inside it, although, I didn't find in the project any table with this feature. Maybe this went unnoticed by me, but If we won't use, then I don't see as benefit to write here. This is very useful I have no doubt, but I would prefer to keep the project as clean as possible only with features that we should rely on.
So, with this in mind, I leave everything related to the Table component to @darlantc review. As a tech leader he is the best choice to evaluate what we should implement or not for this particular project.

2024-07-31 00:23 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +    const message = noResultsMessage ?? "Nenhum resultado encontrado para";
My suggestions for the message here are: 
1. talk with the design team and check the appropriated copy for this case.
2. use English

2024-07-31 00:24 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +      <p>
We already have the Text component, instead of using p tag with strong, I'd recommend to use the Text and TextSpan. We have similar code in the project so you can inspire.

2024-07-31 00:39 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +      <table aria-label="table" className="min-w-full table-auto">
I would improve this aria-label to be more assertive, remember that screen readers can count on this attribute, imagine the scenario where we have 2 tables..
To fix this you can pass aria-label as prop.

2024-07-31 00:48 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +          when={tableColumns.filter(({ label }) => !!label).length > 0}
nit: I believe that you can replace this 
`tableColumns.filter(({ label }) => !!label).length > 0` 
to this:
`tableColumns.some(({ label }) => !!label)`

As I understood, the first one filters out columns without a truthy label and then checks if there are any columns left by comparing the length to 0.
Using the some you can directly checks if there is at least one column with a truthy label without needing to filter and then check the length.

2024-07-31 00:50 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +                      label="Selecionar item"
I suggest to change this label to English

2024-07-31 00:51 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +      label: "Ações",
Same here... use English

2024-07-31 00:52 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +            label="Selecionar todos os itens"
Same here.. use English

2024-07-31 01:12 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +export interface TableColumn {
you are exporting a lot of interfaces without necessity, my suggestion is to create a file for TableTypes. then you can set every type there and share just what you need. We are already doing similar thing on the project, you can use the `DialogBaseTypes` or the `FormTypes` to inspire.

I personally avoid to use Interfaces because they can be merged together. If you declare the same interface multiple times, TypeScript will automatically merge them and this can be a little issue for maintenance if they are declared in different files. But this is just a particular thing why I prefere types instead of interfaces

2024-07-31 01:20 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +export interface TableRow<T> {
nit: this exporting is being used only on the `Table.test.tsx` my suggestion is to avoid as max as possible the imports created because of the tests, ideally they need to rely just what is going on inside the component and we shouldn't create or change anything for tests. That's the reason why we extensively use ComponentProps

2024-07-31 01:27 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +        isLoading: true,
nit: instead of writing isLoading: true every time, you can define on the top of this describe (after line 34) the `const isLoading = true`
and on the getRenderer you can use something like:
`getRenderer({ isLoading })`
If you want to you can apply the same when isLoading = false
this is not an important suggestion and applying or not won't affect the code.

2024-07-31 01:29 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +const NO_RESULTS_MESSAGE = "Nenhum resultado encontrado para";
you need to change the const: `NO_RESULTS_MESSAGE`, `SELECT_ALL_CHECKBOX` and `SELECT_ITEM_CHECKBOX` that are in portuguese

2024-07-31 01:36 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +    });
this test is false positive, this testId does not exist on the project, it is working only because query can return undefined. fix this assertion to find the loading correctly. We already have some parts in the project that are doing similar things, you can use them to inspire. This change is important.

After this I would also suggest to change the text because we don't have a LoadingView component, but we have the Loading component, and this fix can be applied on other parts that you are calling the "LoadingView"

2024-07-31 01:41 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +        expect(queryByTestId("table_thead_th")).not.toBeInTheDocument();
This test is also a false positive, just because you are using the query selector.
The test id `table_thead_th` does not exist on the Table component.
Change the assertion and try to use getByRole associated with name props to find an element.

2024-07-31 01:41 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +        expect(queryByTestId("table_thead_th")).not.toBeInTheDocument();
Same problem of the false positive here.. change the assertion

2024-07-31 01:54 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +        expect(queryByTestId("table_thead_th")).not.toBeInTheDocument();
I suggest to avoid using the `queryByTestId` or `getByTestId`, you should be able to find the elements using the role associated with the prop `name` or combining them with the `within` method.
Using the data-testid in _reusable components_ is considered hardcoding and might to lead to a false positive, that's why relying on labels and roles is always a  better approach.

2024-07-31 02:04 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +            queryByRole("columnheader", { name: "Ações" })
use English instead of Portuguese

2024-07-31 02:04 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.test.tsx
> +            getByRole("columnheader", { name: "Ações" })
same issue about Portuguese here

2024-07-31 02:07 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/TableRowActions.tsx
Is missing the test for this component

2024-07-31 12:10 UTC, yuliaribeiro commented on react-client/src/components/design-system/table/Table.tsx
> +          <div className="scrolling-touch overflow-x-auto">
I'm not an expert in tailwind, but maybe overflow should be `overflow-auto` to include the ability to scroll tables vertically as well.. If this is being applied in another place, please ignore this comment.

2024-07-31 18:14 UTC, mat3usps commented on react-client/src/components/design-system/text/Title.tsx
> +  align?: "center" | "left" | "right" | "justify";
There are designs models that need the align prop for the title, like the one below.

![image](https://github.com/user-attachments/assets/afe7c839-5c73-4f5c-ad01-fbb4c548da55)

2024-07-31 18:16 UTC, mat3usps commented on react-client/src/components/design-system/text/Title.tsx
> +  fullWidth?: boolean;
There are designs that need the width of title to be full to work with centered titles like the one below.

![image](https://github.com/user-attachments/assets/f94f46b1-6397-4ca5-869b-98882c789a90)

2024-08-01 20:49 UTC, merged